// Generated by Melange

import * as Amp_lib_s__Ast from "./ast.js";
import * as Amp_lib_s__Utils from "./utils.js";
import * as Curry from "melange.js/curry.js";
import * as Stdlib__Array from "melange/array.js";
import * as Stdlib__List from "melange/list.js";

function labels_of_cmd(cmd) {
  const match = cmd.desc;
  let tail;
  switch (match.TAG) {
    case /* Return */ 0 :
      tail = /* [] */ 0;
      break;
    case /* Let_ */ 1 :
      tail = labels_of_cmd(match.body);
      break;
    case /* LetCall */ 2 :
    case /* LetTag */ 3 :
      tail = labels_of_cmd(match.body);
      break;
    case /* Match_ */ 4 :
      tail = Stdlib__List.concat_map((function (branch) {
        return labels_of_cmd(branch.body);
      }), match.branches);
      break;
  }
  return {
    hd: cmd.label,
    tl: tail
  };
}

function all_labels(prog) {
  const labels = Stdlib__Array.of_list(Stdlib__List.map((function (prim) {
    return prim[0];
  }), Curry._1(Amp_lib_s__Ast.LabelMap.bindings, prog.ctrl)));
  const ptn_of_label = function (param) {
    
  };
  const labels_of_ptn = function (param) {
    return labels;
  };
  return {
    ptn_of_label: ptn_of_label,
    labels_of_ptn: labels_of_ptn,
    prog: prog
  };
}

function by_function(prog) {
  const label_owner = Stdlib__List.fold_left((function (owners, param) {
    const name = param[0];
    return Stdlib__List.fold_left((function (owners, label) {
      return Curry._3(Amp_lib_s__Ast.LabelMap.add, label, name, owners);
    }), owners, labels_of_cmd(param[1].body));
  }), Amp_lib_s__Ast.LabelMap.empty, Curry._1(Amp_lib_s__Utils.StringMap.bindings, prog.defs));
  const labels_by_function = Curry._1(Amp_lib_s__Utils.StringMap.of_list, Stdlib__List.map((function (param) {
    return [
      param[0],
      Stdlib__Array.of_list(labels_of_cmd(param[1].body))
    ];
  }), Curry._1(Amp_lib_s__Utils.StringMap.bindings, prog.defs)));
  const ptn_of_label = function (label) {
    return Curry._2(Amp_lib_s__Ast.LabelMap.find, label, label_owner);
  };
  const labels_of_ptn = function (name) {
    return Curry._2(Amp_lib_s__Utils.StringMap.find, name, labels_by_function);
  };
  return {
    ptn_of_label: ptn_of_label,
    labels_of_ptn: labels_of_ptn,
    prog: prog
  };
}

export {
  labels_of_cmd,
  all_labels,
  by_function,
}
/* Amp_lib_s__Ast Not a pure module */
