// Generated by Melange

import * as Amp_lib_s__Abs from "./abs.js";
import * as Amp_lib_s__AbsEnvGrammar from "./absEnvGrammar.js";
import * as Amp_lib_s__AbsEnvLexer from "./absEnvLexer.js";
import * as Caml_exceptions from "melange.js/caml_exceptions.js";
import * as Caml_js_exceptions from "melange.js/caml_js_exceptions.js";
import * as Curry from "melange.js/curry.js";
import * as Stdlib__Lexing from "melange/lexing.js";
import * as Stdlib__List from "melange/list.js";
import * as Stdlib__Printf from "melange/printf.js";

const Lex_error = /* @__PURE__ */ Caml_exceptions.create("Amp_lib_s.AbsEnvParser.Lex_error");

function token(lexbuf) {
  const match = Amp_lib_s__AbsEnvLexer.token(lexbuf);
  if (match.NAME === "Fail") {
    throw new Caml_js_exceptions.MelangeError(Lex_error, {
        MEL_EXN_ID: Lex_error,
        _1: match.VAL
      });
  }
  return match.VAL;
}

function at(lexbuf) {
  const pos = lexbuf.lex_curr_p;
  return Curry._2(Stdlib__Printf.sprintf({
    TAG: /* Format */ 0,
    _0: {
      TAG: /* String_literal */ 11,
      _0: "line ",
      _1: {
        TAG: /* Int */ 4,
        _0: /* Int_d */ 0,
        _1: /* No_padding */ 0,
        _2: /* No_precision */ 0,
        _3: {
          TAG: /* String_literal */ 11,
          _0: ", column ",
          _1: {
            TAG: /* Int */ 4,
            _0: /* Int_d */ 0,
            _1: /* No_padding */ 0,
            _2: /* No_precision */ 0,
            _3: /* End_of_format */ 0
          }
        }
      }
    },
    _1: "line %d, column %d"
  }), pos.pos_lnum, pos.pos_cnum - pos.pos_bol | 0);
}

function parse_with(parser, src) {
  const lexbuf = Stdlib__Lexing.from_string(undefined, src);
  try {
    return {
      TAG: /* Ok */ 0,
      _0: Curry._2(parser, token, lexbuf)
    };
  }
  catch (raw_message){
    const message = Caml_js_exceptions.internalToOCamlException(raw_message);
    if (message.MEL_EXN_ID === Lex_error) {
      return {
        TAG: /* Error */ 1,
        _0: Curry._2(Stdlib__Printf.sprintf({
          TAG: /* Format */ 0,
          _0: {
            TAG: /* String */ 2,
            _0: /* No_padding */ 0,
            _1: {
              TAG: /* String_literal */ 11,
              _0: ": ",
              _1: {
                TAG: /* String */ 2,
                _0: /* No_padding */ 0,
                _1: /* End_of_format */ 0
              }
            }
          },
          _1: "%s: %s"
        }), at(lexbuf), message._1)
      };
    }
    if (message.MEL_EXN_ID === Amp_lib_s__AbsEnvGrammar.$$Error) {
      return {
        TAG: /* Error */ 1,
        _0: Curry._1(Stdlib__Printf.sprintf({
          TAG: /* Format */ 0,
          _0: {
            TAG: /* String */ 2,
            _0: /* No_padding */ 0,
            _1: {
              TAG: /* String_literal */ 11,
              _0: ": syntax error",
              _1: /* End_of_format */ 0
            }
          },
          _1: "%s: syntax error"
        }), at(lexbuf))
      };
    }
    throw message;
  }
}

function alloc_static(state) {
  return [
    {
      TAG: /* Static */ 1,
      _0: state.next_static
    },
    {
      next_static: state.next_static + 1 | 0,
      store: state.store
    }
  ];
}

function lower_value(state, value) {
  return Stdlib__List.fold_left((function (param, atom) {
    const match = lower_atom(param[1], atom);
    return [
      Amp_lib_s__Abs.AbsVal.join(param[0], match[0]),
      match[1]
    ];
  }), [
    Amp_lib_s__Abs.AbsVal.bot,
    state
  ], value);
}

function lower_atom(state, atom) {
  if (atom.TAG === /* Int */ 0) {
    return [
      Amp_lib_s__Abs.AbsVal.of_int(atom._0),
      state
    ];
  }
  const match = Stdlib__List.fold_left((function (param, arg) {
    const match = alloc_value(param[1], arg);
    return [
      {
        hd: Curry._1(Amp_lib_s__Abs.VAddr.Abs.singleton, match[0]),
        tl: param[0]
      },
      match[1]
    ];
  }), [
    /* [] */ 0,
    state
  ], atom._1);
  return [
    Amp_lib_s__Abs.AbsVal.of_adt(Amp_lib_s__Abs.AbsAdt.of_tag_args(atom._0, Stdlib__List.rev(match[0]))),
    match[1]
  ];
}

function alloc_value(state, value) {
  const match = alloc_static(state);
  const addr = match[0];
  const match$1 = lower_value(match[1], value);
  const state$1 = match$1[1];
  const store = Curry._3(Amp_lib_s__Abs.AbsVStore.add, addr, match$1[0], state$1.store);
  return [
    addr,
    {
      next_static: state$1.next_static,
      store: store
    }
  ];
}

function lower_env(bindings) {
  const match = Stdlib__List.fold_left((function (param, param$1) {
    const match = alloc_value(param[1], param$1[1]);
    return [
      Curry._3(Amp_lib_s__Abs.AbsEnv.add, param$1[0], Curry._1(Amp_lib_s__Abs.VAddr.Abs.singleton, match[0]), param[0]),
      match[1]
    ];
  }), [
    Amp_lib_s__Abs.AbsEnv.bot,
    {
      next_static: 0,
      store: Amp_lib_s__Abs.AbsVStore.bot
    }
  ], bindings);
  return [
    match[0],
    match[1].store
  ];
}

function parseAbsValue1(src) {
  return parse_with(Amp_lib_s__AbsEnvGrammar.value_eof, src);
}

function parseAbsEnvStore(src) {
  const bindings = parse_with(Amp_lib_s__AbsEnvGrammar.env_eof, src);
  if (bindings.TAG === /* Ok */ 0) {
    return {
      TAG: /* Ok */ 0,
      _0: lower_env(bindings._0)
    };
  } else {
    return {
      TAG: /* Error */ 1,
      _0: bindings._0
    };
  }
}

export {
  Lex_error,
  token,
  at,
  parse_with,
  alloc_static,
  lower_value,
  lower_atom,
  alloc_value,
  lower_env,
  parseAbsValue1,
  parseAbsEnvStore,
}
/* Amp_lib_s__Abs Not a pure module */
