// Generated by Melange

import * as Caml from "melange.js/caml.js";
import * as Stdlib__List from "melange/list.js";
import * as Stdlib__Map from "melange/map.js";
import * as Stdlib__String from "melange/string.js";

const compare = Caml.caml_int_compare;

const Label = {
  compare: compare
};

const LabelMap = Stdlib__Map.Make(Label);

function summary(e) {
  const n = e.desc;
  switch (n.TAG) {
    case /* Num */ 0 :
      return String(n._0);
    case /* Var_ */ 1 :
      return n._0;
    case /* Prim */ 2 :
      return n.op + ("(" + (Stdlib__String.concat(", ", Stdlib__List.map(summary, n.args)) + ")"));
  }
}

const Exp = {
  summary: summary
};

function summary$1(c) {
  const name = c.desc;
  switch (name.TAG) {
    case /* Return */ 0 :
      return "return " + name._0;
    case /* Let_ */ 1 :
      return "let " + (name.x + (" = " + (summary(name.exp) + " in ...")));
    case /* LetCall */ 2 :
      return "let " + (name.x + (" = " + (name.callee + ("(" + (Stdlib__String.concat(", ", name.args) + ") in ...")))));
    case /* LetTag */ 3 :
      return "let " + (name.x + (" = " + (name.tag + ("(" + (Stdlib__String.concat(", ", name.args) + ") in ...")))));
    case /* Match_ */ 4 :
      return "match " + (summary(name.scrutinee) + " with ...");
  }
}

const Cmd = {
  summary: summary$1
};

export {
  Label,
  LabelMap,
  Exp,
  Cmd,
}
/* LabelMap Not a pure module */
