// Generated by Melange

import * as Amp_lib_s__Ast from "./ast.js";
import * as Amp_lib_s__Prims from "./prims.js";
import * as Amp_lib_s__Utils from "./utils.js";
import * as Amp_lib_s__Values from "./values.js";
import * as Curry from "melange.js/curry.js";
import * as Stdlib__Array from "melange/array.js";
import * as Stdlib__List from "melange/list.js";
import * as Stdlib__Option from "melange/option.js";
import * as Stdlib__Printf from "melange/printf.js";
import * as Stdlib__Result from "melange/result.js";
import * as Stdlib__String from "melange/string.js";

function visit_trace_end(end_, visitor) {
  switch (end_.TAG) {
    case /* Final */ 0 :
      return Curry._1(visitor.final, end_.value);
    case /* Stuck */ 1 :
      return Curry._2(visitor.stuck, end_.reason, end_.at);
    case /* Maxed */ 2 :
      return Curry._1(visitor.maxed, end_.reason);
  }
}

function seq(rs) {
  return Stdlib__Result.Syntax.let$plus(Stdlib__List.fold_left((function (acc, r) {
    return Stdlib__Result.Syntax.let$star(acc, (function (xs) {
      return Stdlib__Result.Syntax.let$plus(r, (function (x) {
        return {
          hd: x,
          tl: xs
        };
      }));
    }));
  }), {
    TAG: /* Ok */ 0,
    _0: /* [] */ 0
  }, rs), Stdlib__List.rev);
}

function eval_exp(e, rho) {
  const n = e.desc;
  switch (n.TAG) {
    case /* Num */ 0 :
      return {
        TAG: /* Ok */ 0,
        _0: Amp_lib_s__Values.vInt(n._0)
      };
    case /* Var_ */ 1 :
      const x = n._0;
      const v = Curry._2(Amp_lib_s__Utils.StringMap.find_opt, x, rho);
      if (v !== undefined) {
        return {
          TAG: /* Ok */ 0,
          _0: v
        };
      } else {
        return {
          TAG: /* Error */ 1,
          _0: "undefined variable '" + (x + "'")
        };
      }
    case /* Prim */ 2 :
      const op = n.op;
      return Stdlib__Result.Syntax.let$star(seq(Stdlib__List.map((function (arg) {
        return eval_exp(arg, rho);
      }), n.args)), (function (argVals) {
        return Amp_lib_s__Prims.evalPrim(op, argVals);
      }));
  }
}

function inject(prog, rho) {
  const main = Curry._2(Amp_lib_s__Utils.StringMap.find, prog.mainName, prog.defs);
  return {
    label: main.body.label,
    env: rho,
    kont: /* [] */ 0
  };
}

function mk_step(param, value, detail) {
  const rule = param[3];
  const kont = param[2];
  const env = param[1];
  const label = param[0];
  return Stdlib__Printf.ksprintf((function (s) {
    return {
      TAG: /* Ok */ 0,
      _0: {
        TAG: /* Step */ 0,
        next: {
          label: label,
          env: env,
          kont: kont
        },
        record: {
          rule: rule,
          detail: s,
          value: value
        }
      }
    };
  }), detail);
}

function ffail(reason) {
  return Stdlib__Printf.ksprintf((function (s) {
    return {
      TAG: /* Error */ 1,
      _0: s
    };
  }), reason);
}

function sfail(reason) {
  return {
    TAG: /* Error */ 1,
    _0: reason
  };
}

function step(s, prog) {
  const cmd = Curry._2(Amp_lib_s__Ast.LabelMap.find, s.label, prog.ctrl);
  const x = cmd.desc;
  switch (x.TAG) {
    case /* Return */ 0 :
      const x$1 = x._0;
      return Stdlib__Result.Syntax.let$star(Stdlib__Option.to_result("undefined variable '" + (x$1 + "'"), Curry._2(Amp_lib_s__Utils.StringMap.find_opt, x$1, s.env)), (function (v) {
        const match = s.kont;
        if (!match) {
          return {
            TAG: /* Ok */ 0,
            _0: {
              TAG: /* FinalValue */ 1,
              value: v
            }
          };
        }
        const top = match.hd;
        const suspended = Curry._2(Amp_lib_s__Ast.LabelMap.find, top.label, prog.ctrl);
        const match$1 = suspended.desc;
        if (match$1.TAG !== /* LetCall */ 2) {
          return {
            TAG: /* Error */ 1,
            _0: "invalid continuation frame for return: expected LetCall, got " + Amp_lib_s__Ast.Cmd.summary(suspended)
          };
        }
        const x = match$1.x;
        return Curry._1(mk_step([
          match$1.body.label,
          Curry._3(Amp_lib_s__Utils.StringMap.add, x, v, top.env),
          match.tl,
          /* Return */ "Return"
        ], v, {
          TAG: /* Format */ 0,
          _0: {
            TAG: /* String_literal */ 11,
            _0: "return into ",
            _1: {
              TAG: /* String */ 2,
              _0: /* No_padding */ 0,
              _1: /* End_of_format */ 0
            }
          },
          _1: "return into %s"
        }), x);
      }));
    case /* Let_ */ 1 :
      const body = x.body;
      const x$2 = x.x;
      return Stdlib__Result.Syntax.let$star(eval_exp(x.exp, s.env), (function (v) {
        return Curry._1(mk_step([
          body.label,
          Curry._3(Amp_lib_s__Utils.StringMap.add, x$2, v, s.env),
          s.kont,
          /* LetExp */ "LetExp"
        ], v, {
          TAG: /* Format */ 0,
          _0: {
            TAG: /* String */ 2,
            _0: /* No_padding */ 0,
            _1: {
              TAG: /* String_literal */ 11,
              _0: " := ...",
              _1: /* End_of_format */ 0
            }
          },
          _1: "%s := ..."
        }), x$2);
      }));
    case /* LetCall */ 2 :
      const callee = x.callee;
      const x$3 = x.x;
      const def = Curry._2(Amp_lib_s__Utils.StringMap.find_opt, callee, prog.defs);
      if (def !== undefined) {
        return Stdlib__Result.Syntax.let$star(seq(Stdlib__List.map((function (arg) {
          return Stdlib__Option.to_result("undefined variable " + arg, Curry._2(Amp_lib_s__Utils.StringMap.find_opt, arg, s.env));
        }), x.args)), (function (argVals) {
          const calleeEnv = Amp_lib_s__Values.bindMany(Amp_lib_s__Utils.StringMap.empty, def.params, argVals);
          const frame_label = s.label;
          const frame_env = s.env;
          const frame = {
            label: frame_label,
            env: frame_env
          };
          return Curry._3(mk_step([
            def.body.label,
            calleeEnv,
            {
              hd: frame,
              tl: s.kont
            },
            /* LetCall */ "LetCall"
          ], undefined, {
            TAG: /* Format */ 0,
            _0: {
              TAG: /* String_literal */ 11,
              _0: "call ",
              _1: {
                TAG: /* String */ 2,
                _0: /* No_padding */ 0,
                _1: {
                  TAG: /* Char_literal */ 12,
                  _0: /* '(' */40,
                  _1: {
                    TAG: /* Int */ 4,
                    _0: /* Int_d */ 0,
                    _1: /* No_padding */ 0,
                    _2: /* No_precision */ 0,
                    _3: {
                      TAG: /* String_literal */ 11,
                      _0: " args) -> let ",
                      _1: {
                        TAG: /* String */ 2,
                        _0: /* No_padding */ 0,
                        _1: /* End_of_format */ 0
                      }
                    }
                  }
                }
              }
            },
            _1: "call %s(%d args) -> let %s"
          }), callee, Stdlib__List.length(argVals), x$3);
        }));
      } else {
        return {
          TAG: /* Error */ 1,
          _0: "undefined function " + callee
        };
      }
    case /* LetTag */ 3 :
      const body$1 = x.body;
      const tag = x.tag;
      const x$4 = x.x;
      return Stdlib__Result.Syntax.let$star(seq(Stdlib__List.map((function (arg) {
        return Stdlib__Option.to_result("undefined variable '" + (arg + "'"), Curry._2(Amp_lib_s__Utils.StringMap.find_opt, arg, s.env));
      }), x.args)), (function (argVals) {
        const v = Amp_lib_s__Values.vCtor(tag, argVals);
        return Curry._3(mk_step([
          body$1.label,
          Curry._3(Amp_lib_s__Utils.StringMap.add, x$4, v, s.env),
          s.kont,
          /* LetTag */ "LetTag"
        ], v, {
          TAG: /* Format */ 0,
          _0: {
            TAG: /* String_literal */ 11,
            _0: "let ",
            _1: {
              TAG: /* String */ 2,
              _0: /* No_padding */ 0,
              _1: {
                TAG: /* String_literal */ 11,
                _0: " = ",
                _1: {
                  TAG: /* String */ 2,
                  _0: /* No_padding */ 0,
                  _1: {
                    TAG: /* Char_literal */ 12,
                    _0: /* '(' */40,
                    _1: {
                      TAG: /* Int */ 4,
                      _0: /* Int_d */ 0,
                      _1: /* No_padding */ 0,
                      _2: /* No_precision */ 0,
                      _3: {
                        TAG: /* String_literal */ 11,
                        _0: " args)",
                        _1: /* End_of_format */ 0
                      }
                    }
                  }
                }
              }
            }
          },
          _1: "let %s = %s(%d args)"
        }), x$4, tag, Stdlib__List.length(argVals));
      }));
    case /* Match_ */ 4 :
      const branches = x.branches;
      return Stdlib__Result.Syntax.let$star(eval_exp(x.scrutinee, s.env), (function (v) {
        if (v.TAG === /* Int */ 0) {
          return Curry._1(Stdlib__Printf.ksprintf((function (s) {
            return {
              TAG: /* Error */ 1,
              _0: s
            };
          }), {
            TAG: /* Format */ 0,
            _0: {
              TAG: /* String_literal */ 11,
              _0: "match on non-constructor value (got int ",
              _1: {
                TAG: /* Int */ 4,
                _0: /* Int_d */ 0,
                _1: /* No_padding */ 0,
                _2: /* No_precision */ 0,
                _3: {
                  TAG: /* Char_literal */ 12,
                  _0: /* ')' */41,
                  _1: /* End_of_format */ 0
                }
              }
            },
            _1: "match on non-constructor value (got int %d)"
          }), v._0.n);
        }
        const match = v._0;
        const args = match.args;
        const tag = match.tag;
        return Stdlib__Result.join(Stdlib__Option.to_result("no matching branch for tag '" + (tag + "'"), Stdlib__List.find_map((function (branch) {
          if (branch.tag !== tag) {
            return;
          }
          const env$p = Amp_lib_s__Values.bindMany(s.env, branch.vars, args);
          return Stdlib__Option.some(Curry._2(mk_step([
            branch.body.label,
            env$p,
            s.kont,
            /* Match */ "Match"
          ], v, {
            TAG: /* Format */ 0,
            _0: {
              TAG: /* String */ 2,
              _0: /* No_padding */ 0,
              _1: {
                TAG: /* Char_literal */ 12,
                _0: /* '(' */40,
                _1: {
                  TAG: /* String */ 2,
                  _0: /* No_padding */ 0,
                  _1: {
                    TAG: /* String_literal */ 11,
                    _0: ") matched",
                    _1: /* End_of_format */ 0
                  }
                }
              }
            },
            _1: "%s(%s) matched"
          }), branch.tag, Stdlib__String.concat(", ", branch.vars)));
        }), branches)));
      }));
  }
}

function run_impl(optsOpt, prog, initEnv) {
  const opts = optsOpt !== undefined ? optsOpt : ({
      maxSteps: undefined
    });
  const maxSteps = Stdlib__Option.value(opts.maxSteps, 10000);
  const s0 = inject(prog, initEnv);
  let _i = 0;
  let _cur = s0;
  let _states = {
    hd: s0,
    tl: /* [] */ 0
  };
  let _steps = /* [] */ 0;
  while (true) {
    const steps = _steps;
    const states = _states;
    const cur = _cur;
    const i = _i;
    if (i >= maxSteps) {
      return {
        states: Stdlib__Array.of_list(Stdlib__List.rev(states)),
        steps: Stdlib__Array.of_list(Stdlib__List.rev(steps)),
        end: {
          TAG: /* Maxed */ 2,
          reason: Curry._1(Stdlib__Printf.sprintf({
            TAG: /* Format */ 0,
            _0: {
              TAG: /* String_literal */ 11,
              _0: "exceeded maxSteps=",
              _1: {
                TAG: /* Int */ 4,
                _0: /* Int_d */ 0,
                _1: /* No_padding */ 0,
                _2: /* No_precision */ 0,
                _3: /* End_of_format */ 0
              }
            },
            _1: "exceeded maxSteps=%d"
          }), maxSteps)
        }
      };
    }
    const reason = step(cur, prog);
    if (reason.TAG !== /* Ok */ 0) {
      return {
        states: Stdlib__Array.of_list(Stdlib__List.rev(states)),
        steps: Stdlib__Array.of_list(Stdlib__List.rev(steps)),
        end: {
          TAG: /* Stuck */ 1,
          reason: reason._0,
          at: cur
        }
      };
    }
    const match = reason._0;
    if (match.TAG !== /* Step */ 0) {
      return {
        states: Stdlib__Array.of_list(Stdlib__List.rev(states)),
        steps: Stdlib__Array.of_list(Stdlib__List.rev(steps)),
        end: {
          TAG: /* Final */ 0,
          value: match.value
        }
      };
    }
    const next = match.next;
    _steps = {
      hd: match.record,
      tl: steps
    };
    _states = {
      hd: next,
      tl: states
    };
    _cur = next;
    _i = i + 1 | 0;
    continue;
  };
}

function run(prog, initEnv, opts) {
  if (opts !== undefined) {
    return run_impl(opts, prog, initEnv);
  } else {
    return run_impl(undefined, prog, initEnv);
  }
}

export {
  visit_trace_end,
  seq,
  eval_exp,
  inject,
  mk_step,
  ffail,
  sfail,
  step,
  run_impl,
  run,
}
/* Amp_lib_s__Ast Not a pure module */
