// Generated by Melange

import * as Amp_lib_s__EnvGrammar from "./envGrammar.js";
import * as Amp_lib_s__EnvLexer from "./envLexer.js";
import * as Amp_lib_s__Utils from "./utils.js";
import * as Caml_exceptions from "melange.js/caml_exceptions.js";
import * as Caml_js_exceptions from "melange.js/caml_js_exceptions.js";
import * as Curry from "melange.js/curry.js";
import * as Stdlib__Lexing from "melange/lexing.js";
import * as Stdlib__Printf from "melange/printf.js";

const Lex_error = /* @__PURE__ */ Caml_exceptions.create("Amp_lib_s.EnvParser.Lex_error");

function token(lexbuf) {
  const match = Amp_lib_s__EnvLexer.token(lexbuf);
  if (match.NAME === "Fail") {
    throw new Caml_js_exceptions.MelangeError(Lex_error, {
        MEL_EXN_ID: Lex_error,
        _1: match.VAL
      });
  }
  return match.VAL;
}

function at(lexbuf) {
  const pos = lexbuf.lex_curr_p;
  return Curry._2(Stdlib__Printf.sprintf({
    TAG: /* Format */ 0,
    _0: {
      TAG: /* String_literal */ 11,
      _0: "line ",
      _1: {
        TAG: /* Int */ 4,
        _0: /* Int_d */ 0,
        _1: /* No_padding */ 0,
        _2: /* No_precision */ 0,
        _3: {
          TAG: /* String_literal */ 11,
          _0: ", column ",
          _1: {
            TAG: /* Int */ 4,
            _0: /* Int_d */ 0,
            _1: /* No_padding */ 0,
            _2: /* No_precision */ 0,
            _3: /* End_of_format */ 0
          }
        }
      }
    },
    _1: "line %d, column %d"
  }), pos.pos_lnum, pos.pos_cnum - pos.pos_bol | 0);
}

function parse_with(parser, src) {
  const lexbuf = Stdlib__Lexing.from_string(undefined, src);
  try {
    return {
      TAG: /* Ok */ 0,
      _0: Curry._2(parser, token, lexbuf)
    };
  }
  catch (raw_message){
    const message = Caml_js_exceptions.internalToOCamlException(raw_message);
    if (message.MEL_EXN_ID === Lex_error) {
      return {
        TAG: /* Error */ 1,
        _0: Curry._2(Stdlib__Printf.sprintf({
          TAG: /* Format */ 0,
          _0: {
            TAG: /* String */ 2,
            _0: /* No_padding */ 0,
            _1: {
              TAG: /* String_literal */ 11,
              _0: ": ",
              _1: {
                TAG: /* String */ 2,
                _0: /* No_padding */ 0,
                _1: /* End_of_format */ 0
              }
            }
          },
          _1: "%s: %s"
        }), at(lexbuf), message._1)
      };
    }
    if (message.MEL_EXN_ID === Amp_lib_s__EnvGrammar.$$Error) {
      return {
        TAG: /* Error */ 1,
        _0: Curry._1(Stdlib__Printf.sprintf({
          TAG: /* Format */ 0,
          _0: {
            TAG: /* String */ 2,
            _0: /* No_padding */ 0,
            _1: {
              TAG: /* String_literal */ 11,
              _0: ": syntax error",
              _1: /* End_of_format */ 0
            }
          },
          _1: "%s: syntax error"
        }), at(lexbuf))
      };
    }
    throw message;
  }
}

function parseValue1(src) {
  return parse_with(Amp_lib_s__EnvGrammar.value_eof, src);
}

function parseEnv(src) {
  const bindings = parse_with(Amp_lib_s__EnvGrammar.env_eof, src);
  if (bindings.TAG === /* Ok */ 0) {
    return {
      TAG: /* Ok */ 0,
      _0: Curry._1(Amp_lib_s__Utils.StringMap.of_list, bindings._0)
    };
  } else {
    return {
      TAG: /* Error */ 1,
      _0: bindings._0
    };
  }
}

export {
  Lex_error,
  token,
  at,
  parse_with,
  parseValue1,
  parseEnv,
}
/* Amp_lib_s__EnvGrammar Not a pure module */
