// Generated by Melange

import * as Amp_lib_s__Grammar from "./grammar.js";
import * as Amp_lib_s__Lexer from "./lexer.js";
import * as Amp_lib_s__Utils from "./utils.js";
import * as Curry from "melange.js/curry.js";
import * as Stdlib__Array from "melange/array.js";
import * as Stdlib__Lexing from "melange/lexing.js";
import * as Stdlib__List from "melange/list.js";
import * as Stdlib__Printf from "melange/printf.js";
import * as Stdlib__Result from "melange/result.js";

function error_at(loc, message) {
  return Curry._3(Stdlib__Printf.sprintf({
    TAG: /* Format */ 0,
    _0: {
      TAG: /* String */ 2,
      _0: /* No_padding */ 0,
      _1: {
        TAG: /* String_literal */ 11,
        _0: " at characters ",
        _1: {
          TAG: /* Int */ 4,
          _0: /* Int_d */ 0,
          _1: /* No_padding */ 0,
          _2: /* No_precision */ 0,
          _3: {
            TAG: /* Char_literal */ 12,
            _0: /* '-' */45,
            _1: {
              TAG: /* Int */ 4,
              _0: /* Int_d */ 0,
              _1: /* No_padding */ 0,
              _2: /* No_precision */ 0,
              _3: /* End_of_format */ 0
            }
          }
        }
      }
    },
    _1: "%s at characters %d-%d"
  }), message, loc.from, loc.to_);
}

function validate_program(program) {
  const fun_names = Curry._1(Amp_lib_s__Utils.StringSet.of_list, Stdlib__List.map((function (prim) {
    return prim[0];
  }), Curry._1(Amp_lib_s__Utils.StringMap.bindings, program.defs)));
  const validate_exp = function (e) {
    const match = e.desc;
    switch (match.TAG) {
      case /* Num */ 0 :
      case /* Var_ */ 1 :
        return {
          TAG: /* Ok */ 0,
          _0: undefined
        };
      case /* Prim */ 2 :
        const op = match.op;
        if (Curry._2(Amp_lib_s__Utils.StringSet.mem, op, fun_names)) {
          return {
            TAG: /* Error */ 1,
            _0: error_at(e.loc, "function call '" + (op + "' is not ANF; function calls must appear as let-bound calls with variable arguments"))
          };
        } else {
          return Stdlib__List.fold_left((function (acc, arg) {
            return Stdlib__Result.bind(acc, (function (param) {
              return validate_exp(arg);
            }));
          }), {
            TAG: /* Ok */ 0,
            _0: undefined
          }, match.args);
        }
    }
  };
  const validate_cmd = function (_cmd) {
    while (true) {
      const cmd = _cmd;
      const match = cmd.desc;
      switch (match.TAG) {
        case /* Return */ 0 :
          return {
            TAG: /* Ok */ 0,
            _0: undefined
          };
        case /* Let_ */ 1 :
          const body = match.body;
          return Stdlib__Result.bind(validate_exp(match.exp), (function (param) {
            return validate_cmd(body);
          }));
        case /* LetCall */ 2 :
        case /* LetTag */ 3 :
          _cmd = match.body;
          continue;
        case /* Match_ */ 4 :
          const branches = match.branches;
          return Stdlib__Result.bind(validate_exp(match.scrutinee), (function (param) {
            return Stdlib__List.fold_left((function (acc, branch) {
              return Stdlib__Result.bind(acc, (function (param) {
                return validate_cmd(branch.body);
              }));
            }), {
              TAG: /* Ok */ 0,
              _0: undefined
            }, branches);
          }));
      }
    };
  };
  return Stdlib__List.fold_left((function (acc, param) {
    const def = param[1];
    return Stdlib__Result.bind(acc, (function (param) {
      return validate_cmd(def.body);
    }));
  }), {
    TAG: /* Ok */ 0,
    _0: undefined
  }, Curry._1(Amp_lib_s__Utils.StringMap.bindings, program.defs));
}

function parse(s) {
  const lexbuf = Stdlib__Lexing.from_string(undefined, s);
  let _checkpoint = Amp_lib_s__Grammar.Incremental.program(lexbuf.lex_curr_p);
  let _ranges = /* [] */ 0;
  while (true) {
    const ranges = _ranges;
    const checkpoint = _checkpoint;
    if (!/* tag */ (typeof checkpoint === "number" || typeof checkpoint === "string")) {
      switch (checkpoint.TAG) {
        case /* InputNeeded */ 0 :
          const match = Amp_lib_s__Lexer.token(lexbuf);
          const variant = match.NAME;
          if (variant === "Token") {
            const token = match.VAL;
            const startp = lexbuf.lex_start_p;
            const endp = lexbuf.lex_curr_p;
            const checkpoint$1 = Curry._2(Amp_lib_s__Grammar.MenhirInterpreter.offer, checkpoint, [
              token,
              startp,
              endp
            ]);
            let kind;
            if (/* tag */ typeof token === "number" || typeof token === "string") {
              switch (token) {
                case /* EOF */ 8 :
                  kind = undefined;
                  break;
                case /* WITH */ 0 :
                case /* MATCH */ 3 :
                case /* LET */ 5 :
                case /* IN */ 6 :
                case /* END */ 9 :
                  kind = /* Keyword */ "keyword";
                  break;
                default:
                  kind = /* Punctuation */ "punctuation";
              }
            } else {
              switch (token.TAG) {
                case /* UIDENT */ 0 :
                  kind = /* Constructor */ "constructor";
                  break;
                case /* LIDENT */ 1 :
                  kind = /* Identifier */ "identifier";
                  break;
                case /* INTEGER */ 2 :
                  kind = /* Number */ "number";
                  break;
              }
            }
            const ranges$1 = kind !== undefined ? ({
                hd: {
                  kind: kind,
                  from: startp.pos_cnum,
                  to_: endp.pos_cnum
                },
                tl: ranges
              }) : ranges;
            _ranges = ranges$1;
            _checkpoint = checkpoint$1;
            continue;
          }
          if (variant === "Fail") {
            const pos = lexbuf.lex_curr_p;
            return {
              TAG: /* Error */ 1,
              _0: Curry._3(Stdlib__Printf.sprintf({
                TAG: /* Format */ 0,
                _0: {
                  TAG: /* String_literal */ 11,
                  _0: "Lexing error at line ",
                  _1: {
                    TAG: /* Int */ 4,
                    _0: /* Int_d */ 0,
                    _1: /* No_padding */ 0,
                    _2: /* No_precision */ 0,
                    _3: {
                      TAG: /* String_literal */ 11,
                      _0: ", column ",
                      _1: {
                        TAG: /* Int */ 4,
                        _0: /* Int_d */ 0,
                        _1: /* No_padding */ 0,
                        _2: /* No_precision */ 0,
                        _3: {
                          TAG: /* String_literal */ 11,
                          _0: ": ",
                          _1: {
                            TAG: /* String */ 2,
                            _0: /* No_padding */ 0,
                            _1: /* End_of_format */ 0
                          }
                        }
                      }
                    }
                  }
                },
                _1: "Lexing error at line %d, column %d: %s"
              }), pos.pos_lnum, pos.pos_cnum - pos.pos_bol | 0, match.VAL)
            };
          }
          continue;
        case /* Shifting */ 1 :
        case /* AboutToReduce */ 2 :
          _checkpoint = Curry._2(Amp_lib_s__Grammar.MenhirInterpreter.resume, undefined, checkpoint);
          continue;
        case /* HandlingError */ 3 :
          break;
        case /* Accepted */ 4 :
          const program = checkpoint._0;
          return Stdlib__Result.bind(validate_program(program), (function (param) {
            return {
              TAG: /* Ok */ 0,
              _0: {
                program: program,
                ranges: Stdlib__Array.of_list(Stdlib__List.rev(ranges))
              }
            };
          }));
      }
    }
    const pos$1 = lexbuf.lex_curr_p;
    return {
      TAG: /* Error */ 1,
      _0: Curry._2(Stdlib__Printf.sprintf({
        TAG: /* Format */ 0,
        _0: {
          TAG: /* String_literal */ 11,
          _0: "Syntax error at line ",
          _1: {
            TAG: /* Int */ 4,
            _0: /* Int_d */ 0,
            _1: /* No_padding */ 0,
            _2: /* No_precision */ 0,
            _3: {
              TAG: /* String_literal */ 11,
              _0: ", column ",
              _1: {
                TAG: /* Int */ 4,
                _0: /* Int_d */ 0,
                _1: /* No_padding */ 0,
                _2: /* No_precision */ 0,
                _3: /* End_of_format */ 0
              }
            }
          }
        },
        _1: "Syntax error at line %d, column %d"
      }), pos$1.pos_lnum, pos$1.pos_cnum - pos$1.pos_bol | 0)
    };
  };
}

const let$star = Stdlib__Result.bind;

export {
  error_at,
  let$star,
  validate_program,
  parse,
}
/* Amp_lib_s__Grammar Not a pure module */
