// Generated by Melange

import * as Amp_lib_s__Ast from "./ast.js";
import * as Amp_lib_s__Utils from "./utils.js";
import * as Curry from "melange.js/curry.js";
import * as Stdlib__List from "melange/list.js";
import * as Stdlib__Option from "melange/option.js";

function unit(x, param, ctrl, label) {
  return [
    ctrl,
    label,
    x
  ];
}

function bind(m, f, funNames, ctrl, label) {
  const match = Curry._3(m, funNames, ctrl, label);
  return Curry._4(f, match[2], funNames, match[0], match[1]);
}

function is_fun(ident, funNames, ctrl, label) {
  return [
    ctrl,
    label,
    Curry._2(Amp_lib_s__Utils.StringSet.mem, ident, funNames)
  ];
}

function alloc(param, ctrl, label) {
  return [
    ctrl,
    label + 1 | 0,
    label
  ];
}

function put(label, cmd, param, ctrl, label$p) {
  return [
    Curry._3(Amp_lib_s__Ast.LabelMap.add, label, cmd, ctrl),
    label$p,
    cmd
  ];
}

const M = {
  unit: unit,
  bind: bind,
  is_fun: is_fun,
  alloc: alloc,
  put: put
};

function seq(xs) {
  const partial_arg = Stdlib__List.fold_left((function (acc, x) {
    return function (param, param$1, param$2) {
      return bind(acc, (function (acc) {
        return function (param, param$1, param$2) {
          return bind(x, (function (x) {
            const partial_arg = {
              hd: x,
              tl: acc
            };
            return function (param, param$1, param$2) {
              return [
                param$1,
                param$2,
                partial_arg
              ];
            };
          }), param, param$1, param$2);
        };
      }), param, param$1, param$2);
    };
  }), (function (param, param$1, param$2) {
    return [
      param$1,
      param$2,
      /* [] */ 0
    ];
  }), xs);
  return function (param, param$1, param$2) {
    return bind(partial_arg, (function (xs) {
      const partial_arg = Stdlib__List.rev(xs);
      return function (param, param$1, param$2) {
        return [
          param$1,
          param$2,
          partial_arg
        ];
      };
    }), param, param$1, param$2);
  };
}

function e(param, desc) {
  const partial_arg_loc = {
    from: param[0].pos_cnum,
    to_: param[1].pos_cnum
  };
  const partial_arg = {
    desc: desc,
    loc: partial_arg_loc
  };
  return function (param, param$1, param$2) {
    return [
      param$1,
      param$2,
      partial_arg
    ];
  };
}

function b(param, tag, vars, body) {
  const partial_arg_loc = {
    from: param[0].pos_cnum,
    to_: param[1].pos_cnum
  };
  const partial_arg = {
    tag: tag,
    vars: vars,
    body: body,
    loc: partial_arg_loc
  };
  return function (param, param$1, param$2) {
    return [
      param$1,
      param$2,
      partial_arg
    ];
  };
}

function c(param, desc) {
  const to_ = param[1];
  const from = param[0];
  return function (param, param$1, param$2) {
    return bind(alloc, (function (label) {
      return function (param, param$1, param$2) {
        return bind(desc, (function (desc) {
          const partial_arg_loc = {
            from: from.pos_cnum,
            to_: to_.pos_cnum
          };
          const partial_arg = {
            desc: desc,
            loc: partial_arg_loc,
            label: label
          };
          return function (param, param$1, param$2) {
            return put(label, partial_arg, param, param$1, param$2);
          };
        }), param, param$1, param$2);
      };
    }), param, param$1, param$2);
  };
}

function let_(loc, x, exp, body) {
  return c(loc, (function (param, param$1, param$2) {
    return bind(exp, (function (exp) {
      return function (param, param$1, param$2) {
        return bind(body, (function (body) {
          const match = exp.desc;
          switch (match.TAG) {
            case /* Num */ 0 :
              const partial_arg = {
                TAG: /* Let_ */ 1,
                x: x,
                exp: exp,
                body: body
              };
              return function (param, param$1, param$2) {
                return [
                  param$1,
                  param$2,
                  partial_arg
                ];
              };
            case /* Var_ */ 1 :
              const partial_arg$1 = {
                TAG: /* Let_ */ 1,
                x: x,
                exp: exp,
                body: body
              };
              return function (param, param$1, param$2) {
                return [
                  param$1,
                  param$2,
                  partial_arg$1
                ];
              };
            case /* Prim */ 2 :
              const op = match.op;
              const varArgs = Stdlib__List.map((function (arg) {
                const name = arg.desc;
                switch (name.TAG) {
                  case /* Var_ */ 1 :
                    return name._0;
                  case /* Num */ 0 :
                  case /* Prim */ 2 :
                    return;
                }
              }), match.args);
              return function (param, param$1, param$2) {
                return bind((function (param, param$1, param$2) {
                  return is_fun(op, param, param$1, param$2);
                }), (function (is_fun) {
                  if (is_fun && Stdlib__List.for_all(Stdlib__Option.is_some, varArgs)) {
                    const partial_arg_2 = Stdlib__List.filter_map((function (prim) {
                      return prim;
                    }), varArgs);
                    const partial_arg = {
                      TAG: /* LetCall */ 2,
                      x: x,
                      callee: op,
                      args: partial_arg_2,
                      body: body
                    };
                    return function (param, param$1, param$2) {
                      return [
                        param$1,
                        param$2,
                        partial_arg
                      ];
                    };
                  }
                  const partial_arg$1 = {
                    TAG: /* Let_ */ 1,
                    x: x,
                    exp: exp,
                    body: body
                  };
                  return function (param, param$1, param$2) {
                    return [
                      param$1,
                      param$2,
                      partial_arg$1
                    ];
                  };
                }), param, param$1, param$2);
              };
          }
        }), param, param$1, param$2);
      };
    }), param, param$1, param$2);
  }));
}

function d(param, name, params, body) {
  return {
    name: name,
    params: params,
    body: body,
    loc: {
      from: param[0].pos_cnum,
      to_: param[1].pos_cnum
    }
  };
}

function p(defs) {
  const funNames = Curry._1(Amp_lib_s__Utils.StringSet.of_list, Stdlib__List.map((function (param) {
    return param.name;
  }), defs));
  const mainName = Curry._2(Amp_lib_s__Utils.StringSet.mem, "main", funNames) ? "main" : Stdlib__List.fold_left((function (param, param$1) {
      return param$1.name;
    }), "", defs);
  const match = seq(Stdlib__List.map((function (param) {
    const loc = param.loc;
    const body = param.body;
    const params = param.params;
    const name = param.name;
    return function (param, param$1, param$2) {
      return bind(body, (function (body) {
        const partial_arg = {
          name: name,
          params: params,
          body: body,
          loc: loc
        };
        return function (param, param$1, param$2) {
          return [
            param$1,
            param$2,
            partial_arg
          ];
        };
      }), param, param$1, param$2);
    };
  }), defs))(funNames, Amp_lib_s__Ast.LabelMap.empty, 0);
  return {
    defs: Curry._1(Amp_lib_s__Utils.StringMap.of_list, Stdlib__List.map((function (def) {
      return [
        def.name,
        def
      ];
    }), match[2])),
    mainName: mainName,
    ctrl: match[0]
  };
}

const let$star = bind;

const $great$great$eq = bind;

export {
  M,
  let$star,
  $great$great$eq,
  seq,
  e,
  b,
  c,
  let_,
  d,
  p,
}
/* Amp_lib_s__Ast Not a pure module */
