// Generated by Melange

import * as Amp_lib_s__Values from "./values.js";
import * as Stdlib__Result from "melange/result.js";

function expectArity(op, args, n) {
  if (args.length === n) {
    return {
      TAG: /* Ok */ 0,
      _0: undefined
    };
  } else {
    return {
      TAG: /* Error */ 1,
      _0: "primitive " + (op + (": expected " + (String(n) + (" argument(s), got " + String(args.length)))))
    };
  }
}

function expectInt(op, idx, param) {
  if (param.TAG === /* Int */ 0) {
    return {
      TAG: /* Ok */ 0,
      _0: param._0.n
    };
  } else {
    return {
      TAG: /* Error */ 1,
      _0: "primitive " + (op + (": argument " + (String(idx) + (" expected int, got " + (param._0.tag + "(...)")))))
    };
  }
}

function expectBoolean(op, param) {
  if (param.TAG === /* Int */ 0) {
    return {
      TAG: /* Error */ 1,
      _0: "primitive " + (op + ": expected boolean, got non-boolean")
    };
  }
  const tag = param._0.tag;
  switch (tag) {
    case "False" :
    case "True" :
      return {
        TAG: /* Ok */ 0,
        _0: tag
      };
    default:
      return {
        TAG: /* Error */ 1,
        _0: "primitive " + (op + ": expected boolean, got non-boolean")
      };
  }
}

function boolValue(b) {
  if (b) {
    return Amp_lib_s__Values.vTrue;
  } else {
    return Amp_lib_s__Values.vFalse;
  }
}

function evalPrim(op, args) {
  switch (op) {
    case "add" :
      if (!args) {
        return {
          TAG: /* Error */ 1,
          _0: "unknown primitive or wrong arity: " + op
        };
      }
      const match = args.tl;
      if (!match) {
        return {
          TAG: /* Error */ 1,
          _0: "unknown primitive or wrong arity: " + op
        };
      }
      if (match.tl) {
        return {
          TAG: /* Error */ 1,
          _0: "unknown primitive or wrong arity: " + op
        };
      }
      const v2 = match.hd;
      return Stdlib__Result.bind(expectInt("add", 0, args.hd), (function (n1) {
        return Stdlib__Result.bind(expectInt("add", 1, v2), (function (n2) {
          return {
            TAG: /* Ok */ 0,
            _0: Amp_lib_s__Values.vInt(n1 + n2 | 0)
          };
        }));
      }));
    case "eq" :
      if (!args) {
        return {
          TAG: /* Error */ 1,
          _0: "unknown primitive or wrong arity: " + op
        };
      }
      const match$1 = args.tl;
      if (!match$1) {
        return {
          TAG: /* Error */ 1,
          _0: "unknown primitive or wrong arity: " + op
        };
      }
      if (match$1.tl) {
        return {
          TAG: /* Error */ 1,
          _0: "unknown primitive or wrong arity: " + op
        };
      }
      const v2$1 = match$1.hd;
      return Stdlib__Result.bind(expectInt("eq", 0, args.hd), (function (n1) {
        return Stdlib__Result.bind(expectInt("eq", 1, v2$1), (function (n2) {
          return {
            TAG: /* Ok */ 0,
            _0: n1 === n2 ? Amp_lib_s__Values.vTrue : Amp_lib_s__Values.vFalse
          };
        }));
      }));
    case "iszero" :
      if (args) {
        if (args.tl) {
          return {
            TAG: /* Error */ 1,
            _0: "unknown primitive or wrong arity: " + op
          };
        } else {
          return Stdlib__Result.bind(expectInt("iszero", 0, args.hd), (function (n) {
            return {
              TAG: /* Ok */ 0,
              _0: n === 0 ? Amp_lib_s__Values.vTrue : Amp_lib_s__Values.vFalse
            };
          }));
        }
      } else {
        return {
          TAG: /* Error */ 1,
          _0: "unknown primitive or wrong arity: " + op
        };
      }
    case "lt" :
      if (!args) {
        return {
          TAG: /* Error */ 1,
          _0: "unknown primitive or wrong arity: " + op
        };
      }
      const match$2 = args.tl;
      if (!match$2) {
        return {
          TAG: /* Error */ 1,
          _0: "unknown primitive or wrong arity: " + op
        };
      }
      if (match$2.tl) {
        return {
          TAG: /* Error */ 1,
          _0: "unknown primitive or wrong arity: " + op
        };
      }
      const v2$2 = match$2.hd;
      return Stdlib__Result.bind(expectInt("lt", 0, args.hd), (function (n1) {
        return Stdlib__Result.bind(expectInt("lt", 1, v2$2), (function (n2) {
          return {
            TAG: /* Ok */ 0,
            _0: n1 < n2 ? Amp_lib_s__Values.vTrue : Amp_lib_s__Values.vFalse
          };
        }));
      }));
    case "mul" :
      if (!args) {
        return {
          TAG: /* Error */ 1,
          _0: "unknown primitive or wrong arity: " + op
        };
      }
      const match$3 = args.tl;
      if (!match$3) {
        return {
          TAG: /* Error */ 1,
          _0: "unknown primitive or wrong arity: " + op
        };
      }
      if (match$3.tl) {
        return {
          TAG: /* Error */ 1,
          _0: "unknown primitive or wrong arity: " + op
        };
      }
      const v2$3 = match$3.hd;
      return Stdlib__Result.bind(expectInt("mul", 0, args.hd), (function (n1) {
        return Stdlib__Result.bind(expectInt("mul", 1, v2$3), (function (n2) {
          return {
            TAG: /* Ok */ 0,
            _0: Amp_lib_s__Values.vInt(Math.imul(n1, n2))
          };
        }));
      }));
    case "not" :
      if (args) {
        if (args.tl) {
          return {
            TAG: /* Error */ 1,
            _0: "unknown primitive or wrong arity: " + op
          };
        } else {
          return Stdlib__Result.bind(expectBoolean("not", args.hd), (function (tag) {
            return {
              TAG: /* Ok */ 0,
              _0: tag === "True" ? Amp_lib_s__Values.vFalse : Amp_lib_s__Values.vTrue
            };
          }));
        }
      } else {
        return {
          TAG: /* Error */ 1,
          _0: "unknown primitive or wrong arity: " + op
        };
      }
    case "sub" :
      if (!args) {
        return {
          TAG: /* Error */ 1,
          _0: "unknown primitive or wrong arity: " + op
        };
      }
      const match$4 = args.tl;
      if (!match$4) {
        return {
          TAG: /* Error */ 1,
          _0: "unknown primitive or wrong arity: " + op
        };
      }
      if (match$4.tl) {
        return {
          TAG: /* Error */ 1,
          _0: "unknown primitive or wrong arity: " + op
        };
      }
      const v2$4 = match$4.hd;
      return Stdlib__Result.bind(expectInt("sub", 0, args.hd), (function (n1) {
        return Stdlib__Result.bind(expectInt("sub", 1, v2$4), (function (n2) {
          return {
            TAG: /* Ok */ 0,
            _0: Amp_lib_s__Values.vInt(n1 - n2 | 0)
          };
        }));
      }));
    default:
      return {
        TAG: /* Error */ 1,
        _0: "unknown primitive or wrong arity: " + op
      };
  }
}

const let$star = Stdlib__Result.bind;

export {
  let$star,
  expectArity,
  expectInt,
  expectBoolean,
  boolValue,
  evalPrim,
}
/* Amp_lib_s__Values Not a pure module */
