// Generated by Melange

import * as Amp_lib_s__TraceQueryData from "./traceQueryData.js";
import * as Caml_exceptions from "melange.js/caml_exceptions.js";
import * as Caml_js_exceptions from "melange.js/caml_js_exceptions.js";
import * as Curry from "melange.js/curry.js";
import * as MenhirLib__Engine from "../../vendor/menhirLib/Engine.js";
import * as MenhirLib__InspectionTableInterpreter from "../../vendor/menhirLib/InspectionTableInterpreter.js";
import * as MenhirLib__LinearizedArray from "../../vendor/menhirLib/LinearizedArray.js";
import * as MenhirLib__PackedIntArray from "../../vendor/menhirLib/PackedIntArray.js";
import * as MenhirLib__RowDisplacementDecode from "../../vendor/menhirLib/RowDisplacementDecode.js";
import * as MenhirLib__TableInterpreter from "../../vendor/menhirLib/TableInterpreter.js";

const $$Error = /* @__PURE__ */ Caml_exceptions.create("Amp_lib_s.TraceQueryGrammar.MenhirBasics.Error");

const semantic_action = [
  (function (_menhir_env) {
    const _menhir_stack = _menhir_env.stack;
    const match = _menhir_stack.next.next;
    const _v = {
      TAG: /* And */ 0,
      _0: {
        left: match.semv,
        right: _menhir_stack.semv
      }
    };
    return {
      state: match.state,
      semv: _v,
      startp: match.startp,
      endp: _menhir_stack.endp,
      next: match.next
    };
  }),
  (function (_menhir_env) {
    const _menhir_stack = _menhir_env.stack;
    return {
      state: _menhir_stack.state,
      semv: _menhir_stack.semv,
      startp: _menhir_stack.startp,
      endp: _menhir_stack.endp,
      next: _menhir_stack.next
    };
  }),
  (function (_menhir_env) {
    const _menhir_stack = _menhir_env.stack;
    const match = _menhir_stack.next;
    const _v = {
      TAG: /* Not */ 2,
      _0: _menhir_stack.semv
    };
    return {
      state: match.state,
      semv: _v,
      startp: match.startp,
      endp: _menhir_stack.endp,
      next: match.next
    };
  }),
  (function (_menhir_env) {
    const _menhir_stack = _menhir_env.stack;
    return {
      state: _menhir_stack.state,
      semv: _menhir_stack.semv,
      startp: _menhir_stack.startp,
      endp: _menhir_stack.endp,
      next: _menhir_stack.next
    };
  }),
  (function (_menhir_env) {
    const _menhir_stack = _menhir_env.stack;
    return {
      state: _menhir_stack.state,
      semv: /* EqToken */ 0,
      startp: _menhir_stack.startp,
      endp: _menhir_stack.endp,
      next: _menhir_stack.next
    };
  }),
  (function (_menhir_env) {
    const _menhir_stack = _menhir_env.stack;
    return {
      state: _menhir_stack.state,
      semv: /* NeqToken */ 1,
      startp: _menhir_stack.startp,
      endp: _menhir_stack.endp,
      next: _menhir_stack.next
    };
  }),
  (function (_menhir_env) {
    const _menhir_stack = _menhir_env.stack;
    return {
      state: _menhir_stack.state,
      semv: /* GtToken */ 2,
      startp: _menhir_stack.startp,
      endp: _menhir_stack.endp,
      next: _menhir_stack.next
    };
  }),
  (function (_menhir_env) {
    const _menhir_stack = _menhir_env.stack;
    return {
      state: _menhir_stack.state,
      semv: /* GteToken */ 3,
      startp: _menhir_stack.startp,
      endp: _menhir_stack.endp,
      next: _menhir_stack.next
    };
  }),
  (function (_menhir_env) {
    const _menhir_stack = _menhir_env.stack;
    return {
      state: _menhir_stack.state,
      semv: /* LtToken */ 4,
      startp: _menhir_stack.startp,
      endp: _menhir_stack.endp,
      next: _menhir_stack.next
    };
  }),
  (function (_menhir_env) {
    const _menhir_stack = _menhir_env.stack;
    return {
      state: _menhir_stack.state,
      semv: /* LteToken */ 5,
      startp: _menhir_stack.startp,
      endp: _menhir_stack.endp,
      next: _menhir_stack.next
    };
  }),
  (function (_menhir_env) {
    const _menhir_stack = _menhir_env.stack;
    const match = _menhir_stack.next.next;
    const _v = {
      TAG: /* Or */ 1,
      _0: {
        left: match.semv,
        right: _menhir_stack.semv
      }
    };
    return {
      state: match.state,
      semv: _v,
      startp: match.startp,
      endp: _menhir_stack.endp,
      next: match.next
    };
  }),
  (function (_menhir_env) {
    const _menhir_stack = _menhir_env.stack;
    return {
      state: _menhir_stack.state,
      semv: _menhir_stack.semv,
      startp: _menhir_stack.startp,
      endp: _menhir_stack.endp,
      next: _menhir_stack.next
    };
  }),
  (function (_menhir_env) {
    const _menhir_stack = _menhir_env.stack;
    const match = _menhir_stack.next;
    const match$1 = match.next;
    return {
      state: match$1.state,
      semv: match.semv,
      startp: match$1.startp,
      endp: _menhir_stack.endp,
      next: match$1.next
    };
  }),
  (function (_menhir_env) {
    const _menhir_stack = _menhir_env.stack;
    return {
      state: _menhir_stack.state,
      semv: _menhir_stack.semv,
      startp: _menhir_stack.startp,
      endp: _menhir_stack.endp,
      next: _menhir_stack.next
    };
  }),
  (function (_menhir_env) {
    const _menhir_stack = _menhir_env.stack;
    return {
      state: _menhir_stack.state,
      semv: undefined,
      startp: _menhir_stack.startp,
      endp: _menhir_stack.endp,
      next: _menhir_stack.next
    };
  }),
  (function (_menhir_env) {
    const _menhir_stack = _menhir_env.stack;
    const match = _menhir_stack.next;
    const _v = match.semv;
    return {
      state: match.state,
      semv: _v,
      startp: match.startp,
      endp: _menhir_stack.endp,
      next: match.next
    };
  }),
  (function (_menhir_env) {
    const _menhir_stack = _menhir_env.stack;
    const match = _menhir_stack.next;
    const match$1 = match.next;
    const _startpos_field_name_ = match$1.startp;
    const _v = Amp_lib_s__TraceQueryData.make_field_term(match$1.semv, match.semv, _menhir_stack.semv, _startpos_field_name_.pos_cnum, match.startp.pos_cnum, _menhir_stack.startp.pos_cnum);
    return {
      state: match$1.state,
      semv: _v,
      startp: _startpos_field_name_,
      endp: _menhir_stack.endp,
      next: match$1.next
    };
  }),
  (function (_menhir_env) {
    const _menhir_stack = _menhir_env.stack;
    const _v = {
      TAG: /* Term */ 3,
      _0: {
        field: undefined,
        op: /* Eq */ "eq",
        value: _menhir_stack.semv
      }
    };
    return {
      state: _menhir_stack.state,
      semv: _v,
      startp: _menhir_stack.startp,
      endp: _menhir_stack.endp,
      next: _menhir_stack.next
    };
  }),
  (function (_menhir_env) {
    const _menhir_stack = _menhir_env.stack;
    const _v = {
      TAG: /* Term */ 3,
      _0: {
        field: undefined,
        op: /* Eq */ "eq",
        value: _menhir_stack.semv
      }
    };
    return {
      state: _menhir_stack.state,
      semv: _v,
      startp: _menhir_stack.startp,
      endp: _menhir_stack.endp,
      next: _menhir_stack.next
    };
  }),
  (function (_menhir_env) {
    const _menhir_stack = _menhir_env.stack;
    return {
      state: _menhir_stack.state,
      semv: _menhir_stack.semv,
      startp: _menhir_stack.startp,
      endp: _menhir_stack.endp,
      next: _menhir_stack.next
    };
  }),
  (function (_menhir_env) {
    const _menhir_stack = _menhir_env.stack;
    return {
      state: _menhir_stack.state,
      semv: _menhir_stack.semv,
      startp: _menhir_stack.startp,
      endp: _menhir_stack.endp,
      next: _menhir_stack.next
    };
  })
];

function token2terminal(_tok) {
  if (!/* tag */ (typeof _tok === "number" || typeof _tok === "string")) {
    if (_tok.TAG === /* WORD */ 0) {
      return 1;
    } else {
      return 2;
    }
  }
  switch (_tok) {
    case /* RPAREN */ 0 :
      return 3;
    case /* OR */ 1 :
      return 4;
    case /* NOT */ 2 :
      return 5;
    case /* NEQ */ 3 :
      return 6;
    case /* LTE */ 4 :
      return 7;
    case /* LT */ 5 :
      return 8;
    case /* LPAREN */ 6 :
      return 9;
    case /* GTE */ 7 :
      return 10;
    case /* GT */ 8 :
      return 11;
    case /* EQ */ 9 :
      return 12;
    case /* EOF */ 10 :
      return 13;
    case /* AND */ 11 :
      return 14;
  }
}

function token2value(_tok) {
  if (/* tag */ typeof _tok === "number" || typeof _tok === "string") {
    return;
  } else {
    return _tok._0;
  }
}

function default_reduction(i) {
  return MenhirLib__PackedIntArray.get8("\0\0\x07\x0b\n\t\b\x06\0\x15\x16\x12\x14\0\0\x0f\x05\0\x0e\0\x03\0\0\x02\0\x04\x10\x01\0\x11", i);
}

function error(i, j) {
  return MenhirLib__PackedIntArray.get1("dD7|\0\0\0\0\0\0\0\0\0\0\0`\0\0\0\0\0\0\0\0\f\x88\x19\x10\0\0\0\x000\0\0\x03\"\0\0\x03\0\xd9\x10\0\0\x18\x06\0\0\0\0\0\0\x80@\0\0", Math.imul(15, i) + j | 0);
}

function action(i, j) {
  const k = MenhirLib__RowDisplacementDecode.decode(MenhirLib__PackedIntArray.get8("\x16\x07\0\0\0\0\0\0\x1a\0\0\0\0\x16\x16\0\0,\0\x16\0$\x16\0\x1c\0\0\0,\0", i));
  return MenhirLib__PackedIntArray.get8("II\0\n\x0e\x12\0\x16\x1a\x1eII\x062&*611\0:--\0kJN1Z\0\0-Z\0\0w", k + j | 0);
}

function lhs(i) {
  return MenhirLib__PackedIntArray.get4("\b\x87vffeTC2\"\x11", i);
}

function $$goto(i, j) {
  const k = MenhirLib__RowDisplacementDecode.decode(MenhirLib__PackedIntArray.get8("\x05\x05\0\0\0\0\0\0\x0e\0\0\0\0&\n\0\0\0\0\x18\0\0(\0\0\0\0\0\0\0", i));
  return MenhirLib__PackedIntArray.get8("\x10\x1c\x11\x1d\t\x15\x19\x10\f\x11\x12\0\x15\x19\x10\0\x11\0\0\x15\x16\x10\x10\x11\x11\0\x1a\x18", k + j | 0);
}

const ET = MenhirLib__TableInterpreter.MakeEngineTable({
  terminal_count: 15,
  token2terminal: token2terminal,
  error_terminal: 0,
  token2value: token2value,
  default_reduction: default_reduction,
  error: error,
  action: action,
  lhs: lhs,
  $$goto: $$goto,
  start: 1,
  semantic_action: semantic_action,
  $$Error: $$Error,
  trace: undefined
});

const TI = MenhirLib__Engine.Make(ET);

const entry = TI.entry;

const start = TI.start;

const Symbols = {};

MenhirLib__InspectionTableInterpreter.Symbols(Symbols);

function terminal(t) {
  switch (t) {
    case 0 :
      return {
        TAG: /* X */ 0,
        _0: {
          TAG: /* T */ 0,
          _0: /* T_error */ 0
        }
      };
    case 1 :
      return {
        TAG: /* X */ 0,
        _0: {
          TAG: /* T */ 0,
          _0: /* T_WORD */ 1
        }
      };
    case 2 :
      return {
        TAG: /* X */ 0,
        _0: {
          TAG: /* T */ 0,
          _0: /* T_STRING */ 2
        }
      };
    case 3 :
      return {
        TAG: /* X */ 0,
        _0: {
          TAG: /* T */ 0,
          _0: /* T_RPAREN */ 3
        }
      };
    case 4 :
      return {
        TAG: /* X */ 0,
        _0: {
          TAG: /* T */ 0,
          _0: /* T_OR */ 4
        }
      };
    case 5 :
      return {
        TAG: /* X */ 0,
        _0: {
          TAG: /* T */ 0,
          _0: /* T_NOT */ 5
        }
      };
    case 6 :
      return {
        TAG: /* X */ 0,
        _0: {
          TAG: /* T */ 0,
          _0: /* T_NEQ */ 6
        }
      };
    case 7 :
      return {
        TAG: /* X */ 0,
        _0: {
          TAG: /* T */ 0,
          _0: /* T_LTE */ 7
        }
      };
    case 8 :
      return {
        TAG: /* X */ 0,
        _0: {
          TAG: /* T */ 0,
          _0: /* T_LT */ 8
        }
      };
    case 9 :
      return {
        TAG: /* X */ 0,
        _0: {
          TAG: /* T */ 0,
          _0: /* T_LPAREN */ 9
        }
      };
    case 10 :
      return {
        TAG: /* X */ 0,
        _0: {
          TAG: /* T */ 0,
          _0: /* T_GTE */ 10
        }
      };
    case 11 :
      return {
        TAG: /* X */ 0,
        _0: {
          TAG: /* T */ 0,
          _0: /* T_GT */ 11
        }
      };
    case 12 :
      return {
        TAG: /* X */ 0,
        _0: {
          TAG: /* T */ 0,
          _0: /* T_EQ */ 12
        }
      };
    case 13 :
      return {
        TAG: /* X */ 0,
        _0: {
          TAG: /* T */ 0,
          _0: /* T_EOF */ 13
        }
      };
    case 14 :
      return {
        TAG: /* X */ 0,
        _0: {
          TAG: /* T */ 0,
          _0: /* T_AND */ 14
        }
      };
    default:
      throw new Caml_js_exceptions.MelangeError("Assert_failure", {
          MEL_EXN_ID: "Assert_failure",
          _1: [
            "lib/s/traceQueryGrammar.ml",
            917,
            12
          ]
        });
  }
}

function nonterminal(nt) {
  switch (nt) {
    case 1 :
      return {
        TAG: /* X */ 0,
        _0: {
          TAG: /* N */ 1,
          _0: /* N_value_token */ 0
        }
      };
    case 2 :
      return {
        TAG: /* X */ 0,
        _0: {
          TAG: /* N */ 1,
          _0: /* N_term */ 1
        }
      };
    case 3 :
      return {
        TAG: /* X */ 0,
        _0: {
          TAG: /* N */ 1,
          _0: /* N_query_eof */ 2
        }
      };
    case 4 :
      return {
        TAG: /* X */ 0,
        _0: {
          TAG: /* N */ 1,
          _0: /* N_primary */ 3
        }
      };
    case 5 :
      return {
        TAG: /* X */ 0,
        _0: {
          TAG: /* N */ 1,
          _0: /* N_or_expr */ 4
        }
      };
    case 6 :
      return {
        TAG: /* X */ 0,
        _0: {
          TAG: /* N */ 1,
          _0: /* N_operator */ 5
        }
      };
    case 7 :
      return {
        TAG: /* X */ 0,
        _0: {
          TAG: /* N */ 1,
          _0: /* N_not_expr */ 6
        }
      };
    case 8 :
      return {
        TAG: /* X */ 0,
        _0: {
          TAG: /* N */ 1,
          _0: /* N_and_expr */ 7
        }
      };
    default:
      throw new Caml_js_exceptions.MelangeError("Assert_failure", {
          MEL_EXN_ID: "Assert_failure",
          _1: [
            "lib/s/traceQueryGrammar.ml",
            939,
            12
          ]
        });
  }
}

function lr0_incoming(i) {
  return MenhirLib__PackedIntArray.get8("\0\x04\x0e\x10\x12\x16\x18\x1a\r\x04\x06\x03\x06\f\x14\x05\t\x0b\b\n\x0f\x11\x1e\x0f\x11\x0f\x1c\x07\x0b\x1c", i);
}

function rhs_data(i) {
  return MenhirLib__PackedIntArray.get8("\x07\x11\x1e\x0f\x0f\f\x0f\t\x1a\x0e\x18\x16\x12\x10\x0b\n\x11\x11\x14\x0b\b\x05\x1c\x0b\x1c\x04\r\x03\x04\x06\x04\x06", i);
}

function rhs_entry(i) {
  return MenhirLib__PackedIntArray.get8("\0\x01\x04\x05\x07\b\t\n\x0b\f\r\x0e\x11\x12\x15\x16\x17\x19\x1c\x1d\x1e\x1f ", i);
}

function rhs(i) {
  return MenhirLib__LinearizedArray.read_row_via(rhs_data, rhs_entry, i);
}

function lr0_core(i) {
  return MenhirLib__PackedIntArray.get8("\0\x01\x02\x03\x04\x05\x06\x07\b\t\n\x0b\f\r\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d", i);
}

function lr0_items_data(i) {
  return MenhirLib__PackedIntArray.get16("\0\0H\x01D\x01\x18\x01(\x01$\x01 \x01\x1c\x01\x14\x01D\x02P\x01T\x01D\x03L\x01\f\x014\x018\x01\x10\x014\x02,\x014\x03,\x02\b\x01,\x03\x04\x01\x04\x02\x04\x030\x01\x04\x01\f\x02<\x01\0\x01@\x01,\x01@\x02", i);
}

function lr0_items_entry(i) {
  return MenhirLib__PackedIntArray.get8("\0\x01\x03\x04\x05\x06\x07\b\t\n\x0b\f\r\x0e\x0f\x10\x11\x12\x14\x15\x16\x17\x19\x1a\x1b\x1d\x1e\x1f \"#", i);
}

function lr0_items(i) {
  return MenhirLib__LinearizedArray.read_row_via(lr0_items_data, lr0_items_entry, i);
}

function nullable(i) {
  return MenhirLib__PackedIntArray.get1("\0\0", i);
}

function first(i, j) {
  return MenhirLib__PackedIntArray.get1("dD\xc0\x01\x80\x03\"&\x04\f\x88\0\xee2 d@", Math.imul(15, i) + j | 0);
}

const include = MenhirLib__InspectionTableInterpreter.Make({
  terminal_count: 15,
  token2terminal: token2terminal,
  error_terminal: 0,
  token2value: token2value,
  default_reduction: default_reduction,
  error: error,
  action: action,
  lhs: lhs,
  $$goto: $$goto,
  start: 1,
  semantic_action: semantic_action,
  $$Error: $$Error,
  trace: undefined
}, {
  terminal: terminal,
  nonterminal: nonterminal,
  rhs: rhs,
  lr0_core: lr0_core,
  lr0_items: lr0_items,
  lr0_incoming: lr0_incoming,
  nullable: nullable,
  first: first
}, ET, {});

function query_eof(lexer, lexbuf) {
  return Curry._4(entry, "Legacy", 0, lexer, lexbuf);
}

function query_eof$1(initial_position) {
  return Curry._2(start, 0, initial_position);
}

const Incremental = {
  query_eof: query_eof$1
};

const MenhirInterpreter_offer = TI.offer;

const MenhirInterpreter_resume = TI.resume;

const MenhirInterpreter_lexer_lexbuf_to_supplier = TI.lexer_lexbuf_to_supplier;

const MenhirInterpreter_loop = TI.loop;

const MenhirInterpreter_loop_handle = TI.loop_handle;

const MenhirInterpreter_loop_handle_undo = TI.loop_handle_undo;

const MenhirInterpreter_shifts = TI.shifts;

const MenhirInterpreter_acceptable = TI.acceptable;

const MenhirInterpreter_number = TI.number;

const MenhirInterpreter_production_index = TI.production_index;

const MenhirInterpreter_find_production = TI.find_production;

const MenhirInterpreter_top = TI.top;

const MenhirInterpreter_pop_many = TI.pop_many;

const MenhirInterpreter_get = TI.get;

const MenhirInterpreter_current_state_number = TI.current_state_number;

const MenhirInterpreter_equal = TI.equal;

const MenhirInterpreter_positions = TI.positions;

const MenhirInterpreter_env_has_default_reduction = TI.env_has_default_reduction;

const MenhirInterpreter_state_has_default_reduction = TI.state_has_default_reduction;

const MenhirInterpreter_pop = TI.pop;

const MenhirInterpreter_force_reduction = TI.force_reduction;

const MenhirInterpreter_input_needed = TI.input_needed;

const MenhirInterpreter_compare_terminals = include.compare_terminals;

const MenhirInterpreter_compare_nonterminals = include.compare_nonterminals;

const MenhirInterpreter_compare_symbols = include.compare_symbols;

const MenhirInterpreter_compare_productions = include.compare_productions;

const MenhirInterpreter_compare_items = include.compare_items;

const MenhirInterpreter_incoming_symbol = include.incoming_symbol;

const MenhirInterpreter_items = include.items;

const MenhirInterpreter_lhs = include.lhs;

const MenhirInterpreter_rhs = include.rhs;

const MenhirInterpreter_nullable = include.nullable;

const MenhirInterpreter_first = include.first;

const MenhirInterpreter_xfirst = include.xfirst;

const MenhirInterpreter_foreach_terminal = include.foreach_terminal;

const MenhirInterpreter_foreach_terminal_but_error = include.foreach_terminal_but_error;

const MenhirInterpreter_feed = include.feed;

const MenhirInterpreter = {
  offer: MenhirInterpreter_offer,
  resume: MenhirInterpreter_resume,
  lexer_lexbuf_to_supplier: MenhirInterpreter_lexer_lexbuf_to_supplier,
  loop: MenhirInterpreter_loop,
  loop_handle: MenhirInterpreter_loop_handle,
  loop_handle_undo: MenhirInterpreter_loop_handle_undo,
  shifts: MenhirInterpreter_shifts,
  acceptable: MenhirInterpreter_acceptable,
  number: MenhirInterpreter_number,
  production_index: MenhirInterpreter_production_index,
  find_production: MenhirInterpreter_find_production,
  top: MenhirInterpreter_top,
  pop_many: MenhirInterpreter_pop_many,
  get: MenhirInterpreter_get,
  current_state_number: MenhirInterpreter_current_state_number,
  equal: MenhirInterpreter_equal,
  positions: MenhirInterpreter_positions,
  env_has_default_reduction: MenhirInterpreter_env_has_default_reduction,
  state_has_default_reduction: MenhirInterpreter_state_has_default_reduction,
  pop: MenhirInterpreter_pop,
  force_reduction: MenhirInterpreter_force_reduction,
  input_needed: MenhirInterpreter_input_needed,
  compare_terminals: MenhirInterpreter_compare_terminals,
  compare_nonterminals: MenhirInterpreter_compare_nonterminals,
  compare_symbols: MenhirInterpreter_compare_symbols,
  compare_productions: MenhirInterpreter_compare_productions,
  compare_items: MenhirInterpreter_compare_items,
  incoming_symbol: MenhirInterpreter_incoming_symbol,
  items: MenhirInterpreter_items,
  lhs: MenhirInterpreter_lhs,
  rhs: MenhirInterpreter_rhs,
  nullable: MenhirInterpreter_nullable,
  first: MenhirInterpreter_first,
  xfirst: MenhirInterpreter_xfirst,
  foreach_terminal: MenhirInterpreter_foreach_terminal,
  foreach_terminal_but_error: MenhirInterpreter_foreach_terminal_but_error,
  feed: MenhirInterpreter_feed
};

const Tables = {
  terminal_count: 15,
  token2terminal: token2terminal,
  error_terminal: 0,
  token2value: token2value,
  default_reduction: default_reduction,
  error: error,
  action: action,
  lhs: lhs,
  $$goto: $$goto,
  start: 1,
  semantic_action: semantic_action,
  $$Error: $$Error,
  trace: undefined
};

export {
  $$Error,
  query_eof,
  MenhirInterpreter,
  Incremental,
  Tables,
}
/* ET Not a pure module */
