// Generated by Melange

import * as Stdlib__Int from "melange/int.js";
import * as Stdlib__Map from "melange/map.js";
import * as Stdlib__Set from "melange/set.js";
import * as Stdlib__String from "melange/string.js";

const MapMake = Stdlib__Map.Make;

const StringMap = Stdlib__Map.Make({
  compare: Stdlib__String.compare
});

const IntMap = Stdlib__Map.Make({
  compare: Stdlib__Int.compare
});

const StringSet = Stdlib__Set.Make({
  compare: Stdlib__String.compare
});

export {
  MapMake,
  StringMap,
  IntMap,
  StringSet,
}
/* StringMap Not a pure module */
